// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfmFaE9Z09AoZFAocizNxN0kvNAkVe2rc',
    appId: '1:822989077339:web:60cb9b8fc22705a94b787e',
    messagingSenderId: '822989077339',
    projectId: 'final-project-sanber-8773e',
    authDomain: 'final-project-sanber-8773e.firebaseapp.com',
    storageBucket: 'final-project-sanber-8773e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKmSm4mkLnoXmEh5ZiV87uuwHhJMrVI-Y',
    appId: '1:822989077339:android:bc981f59a19fe0934b787e',
    messagingSenderId: '822989077339',
    projectId: 'final-project-sanber-8773e',
    storageBucket: 'final-project-sanber-8773e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmBfkEZy9OcWNLWbTpg1p07yxCsJ-5IAM',
    appId: '1:822989077339:ios:09beb4ed8e4b906b4b787e',
    messagingSenderId: '822989077339',
    projectId: 'final-project-sanber-8773e',
    storageBucket: 'final-project-sanber-8773e.appspot.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmBfkEZy9OcWNLWbTpg1p07yxCsJ-5IAM',
    appId: '1:822989077339:ios:09beb4ed8e4b906b4b787e',
    messagingSenderId: '822989077339',
    projectId: 'final-project-sanber-8773e',
    storageBucket: 'final-project-sanber-8773e.appspot.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfmFaE9Z09AoZFAocizNxN0kvNAkVe2rc',
    appId: '1:822989077339:web:c4d1779ba53cf6214b787e',
    messagingSenderId: '822989077339',
    projectId: 'final-project-sanber-8773e',
    authDomain: 'final-project-sanber-8773e.firebaseapp.com',
    storageBucket: 'final-project-sanber-8773e.appspot.com',
  );
}
